import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';

export async function POST(request: Request) {
    let prompt = '';
    try {
        const json = await request.json();
        prompt = json.prompt;

        if (!prompt) {
            return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
        }

        console.log("Attempting to generate with Gemini API...");
        const geminiKey = process.env.GEMINI_API_KEY;

        if (!geminiKey) {
            return NextResponse.json({ error: "Kein Gemini API Key konfiguriert. Bitte prüfe die Einstellungen." }, { status: 400 });
        }

        const ai = new GoogleGenAI({ apiKey: geminiKey });
        const response = await ai.models.generateContent({
            model: 'gemini-3.1-flash-image-preview',
            contents: {
                parts: [{ text: prompt }],
            },
            config: {
                imageConfig: {
                    aspectRatio: "1:1",
                    imageSize: "1K"
                }
            }
        });

        let imageUrl = '';
        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                const base64EncodeString = part.inlineData.data;
                imageUrl = `data:image/png;base64,${base64EncodeString}`;
                break;
            }
        }

        if (imageUrl) {
            console.log("Successfully generated with Gemini!");
            return NextResponse.json({ image: imageUrl });
        } else {
            // Check if there's text feedback instead of an image
            const textPart = response.candidates?.[0]?.content?.parts?.find(p => p.text);
            if (textPart?.text) {
                throw new Error(`Gemini hat kein Bild generiert, sondern Text: ${textPart.text}`);
            }
            throw new Error('No image generated by Gemini');
        }

    } catch (error: any) {
        console.error('Gemini API error details:', error);
        let errorMsg = "Ein unerwarteter Fehler ist aufgetreten.";

        if (error.message?.includes("API_KEY_INVALID") || error.message?.includes("API key not valid") || error.message?.includes("400")) {
            errorMsg = "Der angegebene Gemini API Key ist ungültig oder nicht für Bildgenerierung berechtigt. Bitte prüfe deinen Key im Google AI Studio.";
        } else if (error.status === 429 || error.message?.includes('429') || error.message?.includes('quota')) {
            errorMsg = "Gemini Rate Limit erreicht. Bitte kurz warten.";
        } else {
            errorMsg = "Gemini API Fehler: " + (error.message || "Unbekannter Fehler");
        }

        return NextResponse.json({ error: errorMsg }, { status: 500 });
    }
}
